baseURL = 'https://www.huwan.org/'
theme = ["xmin"]

title = ' HwP: Hardware Programmer'
author = "Huwan Peng"
languageCode = "en-US"

[params]
  footer = "Copyright © {Year}, Huwan Peng."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
